security:
  # Configuration des password hashers
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"
    App\Entity\User:
      algorithm: auto

  # Configuration des providers
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  # Configuration des firewalls
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      pattern: ^/
      lazy: true
      provider: app_user_provider
      form_login:
        login_path: connexion
        check_path: connexion
        username_parameter: email
        password_parameter: password
        default_target_path: home
        always_use_default_target_path: false
      logout:
        path: deconnexion
        target: connexion

  # Contrôle des accès
  access_control:
    # - { path: ^/admin, roles: ROLE_ADMIN }
    # - { path: ^/profile, roles: ROLE_USER }

when@test:
  security:
    # Réduction des ressources pour les tests
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4 # Valeur minimale pour bcrypt
        time_cost: 3 # Valeur minimale pour argon
        memory_cost: 10 # Valeur minimale pour argon
