controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_reset_password:
  path: /reset-password/{token}
  controller: App\Controller\Admin\ResetUserPasswordController::resetPassword